name: Preview Hosting on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Firebase Preview Channel
        # this creates a preview channel "pr-<PR_NUMBER>"
        uses: w9jds/firebase-action@v3
        with:
          args: deploy --only hosting:channel:pr-${{ github.event.number }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
